describe('Company Test',()=>{
        it('should enter main page',()=>{
            cy.visit('https://vending-main-client-dev.rvvcs.com/auth/login');
            cy.get('input[class="v-field__input"]').eq(0).type('admin');
            cy.get('input[class="v-field__input"]').eq(1).type('123456');
            cy.get('input[type="checkbox"]').check();
            cy.get("#__nuxt > div > div > div > div > div > div > div > div.v-card-item.py-8.pa-sm-8.pa-md-15 > div > div > div:nth-child(2) > div:nth-child(4) > button").click()
            cy.wait(1000)
            cy.get('nav[class="v-navigation-drawer v-navigation-drawer--left v-navigation-drawer--temporary v-navigation-drawer--active v-theme--PurpleTheme v-navigation-drawer--mobile elevation-0 leftSidebar"]')
            cy.wait(1000)
            cy.get('div[class="v-navigation-drawer__scrim"]').click()
            cy.wait(1000)
        })
        it('should enter company',()=>{
            cy.get('button[class="v-btn v-btn--icon v-theme--PurpleTheme v-btn--density-default v-btn--size-small v-btn--variant-flat ms-md-3 ms-sm-5 ms-3 text-muted"]').click()
            cy.wait(1000)
            cy.get('#__nuxt > div > div > div > div > nav > div > div:nth-child(2) > div > div.v-list.v-theme--PurpleTheme.bg-transparent.v-list--density-default.v-list--one-line.pa-6 > a:nth-child(3)').wait(2000).should('be.visible').click()
        })
        it('search test001',()=>{
            cy.get('input[class="v-field__input"]').click().type('test001')
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.wait(1000)
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text"]').eq(1).wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เริ่มต้นด้วย').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ลงท้ายด้วย').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เท่ากับ').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่มี').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.contains('ไม่เท่ากับ').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-muted v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(2000)
        })
        it('insert new company',()=>{
            cy.get('a[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default elevation-3 v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.get('button[class="swal2-confirm swal2-styled"]').wait(1000).click()
            cy.get('input[class="v-field__input"]').eq(1).wait(1000).click().type('test001')
            cy.get('input[type="checkbox"]').wait(1000).click().wait(1000).click()
            cy.get('textarea[class="v-field__input"]').wait(1000).click().type('12345')
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
            cy.wait(2000)
        })
        it('search test001 again',()=>{
            cy.get('input[class="v-field__input"]').click().type('test001')
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text"]').eq(1).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เริ่มต้นด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ลงท้ายด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่มี').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-muted v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
        })
        it('check data of test001',()=>{
            cy.get('i[class="mdi-dots-vertical mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default"]').eq(3).wait(1000).click()
            cy.get('a[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-compact v-list-item--one-line rounded-0 v-list-item--variant-text cursor-pointer"]').wait(1000).click()
            cy.get('input[value="test001"]').wait(1000).click()
            cy.get('input[type="checkbox"]').wait(1000).click().wait(1000).click()
            cy.get('textarea[value="12345"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
            cy.wait(2000)
        })
        it('update test001 to test002',()=>{
            cy.get('i[class="mdi-dots-vertical mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default"]').eq(3).wait(1000).click()
            cy.get('a[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-compact v-list-item--one-line rounded-0 v-list-item--variant-text cursor-pointer"]').wait(1000).click()
            cy.get('input[value="test001"]').wait(1000).clear()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.get('button[class="swal2-confirm swal2-styled"]').wait(1000).click()
            cy.get('input[class="v-field__input"]').eq(1).wait(1000).click().type('test002')
            cy.get('input[type="checkbox"]').wait(1000).click().wait(1000).click()
            cy.get('textarea[value="12345"]').wait(1000).clear()
            cy.get('textarea[class="v-field__input"]').wait(1000).click().type('67890')
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click().wait(1000)
            cy.wait(1000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
            cy.wait(2000)
        })
        it('search not found test001',()=>{
            cy.get('input[class="v-field__input"]').click().type('test001')
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text"]').eq(1).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เริ่มต้นด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ลงท้ายด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่มี').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-muted v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(2000)
        })
        it('search found test002',()=>{
            cy.get('input[class="v-field__input"]').click().type('test002')
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text"]').eq(1).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เริ่มต้นด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ลงท้ายด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่มี').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-muted v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(2000)
        })
        it('check data of test002',()=>{
            cy.get('i[class="mdi-dots-vertical mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default"]').eq(3).wait(1000).click()
            cy.get('a[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-compact v-list-item--one-line rounded-0 v-list-item--variant-text cursor-pointer"]').click()
            cy.get('input[value="test002"]').wait(1000).click()
            cy.get('input[type="checkbox"]').wait(1000).click().wait(1000).click()
            cy.get('textarea[value="67890"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-save v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
            cy.wait(2000)
        })
        it('delete test002',()=>{
            cy.get('i[class="mdi-dots-vertical mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default"]').eq(3).wait(1000).click()
            cy.wait(1000)
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-compact v-list-item--one-line rounded-0 v-list-item--variant-text cursor-pointer"]').wait(1000).click()
            cy.wait(2000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
            cy.wait(1000)
            cy.get('button[class="swal2-confirm swal2-styled"]').click()
        })
        it('search not found test002',()=>{
            cy.get('input[class="v-field__input"]').click().type('test002')
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('div[class="v-list-item v-list-item--link v-theme--PurpleTheme v-list-item--density-default v-list-item--one-line rounded-0 v-list-item--variant-text"]').eq(1).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(1).wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เริ่มต้นด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ลงท้ายด้วย').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่มี').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('i[class="mdi-menu-down mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default v-select__menu-icon"]').eq(2).wait(1000).click()
            cy.wait(1000)
            cy.contains('ไม่เท่ากับ').wait(1000).click()
            cy.wait(1000)
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(1000)
            cy.get('i[class="mdi-filter mdi v-icon notranslate v-theme--PurpleTheme v-icon--size-default text-primary v-icon--clickable"]').wait(1000).click()
            cy.get('button[class="v-btn v-btn--elevated v-theme--PurpleTheme bg-muted v-btn--density-default v-btn--size-default v-btn--variant-elevated"]').wait(1000).click()
            cy.wait(2000)
        })
    })  
        

